import generatedContractSchemas from "./generated/contract-schemas.json" with {
	type: "json",
};
import type { NormalizedContractSchema } from "./json";

const contracts = generatedContractSchemas as unknown as Readonly<{
	campaignGetInputContract: NormalizedContractSchema;
	campaignGetOutputContract: NormalizedContractSchema;
	paginationInputContract: NormalizedContractSchema;
	resourceIdInputContract: NormalizedContractSchema;
	subscriberListRecordContract: NormalizedContractSchema;
	subscriberListCollectionOutputContract: NormalizedContractSchema;
	subscriberRecordContract: NormalizedContractSchema;
	subscriberListInputContract: NormalizedContractSchema;
	subscriberCollectionOutputContract: NormalizedContractSchema;
	campaignListInputContract: NormalizedContractSchema;
	campaignCollectionOutputContract: NormalizedContractSchema;
	campaignStatsOutputContract: NormalizedContractSchema;
	templateRecordContract: NormalizedContractSchema;
	templateCreateInputContract: NormalizedContractSchema;
	templateUpdateInputContract: NormalizedContractSchema;
	templateDeleteOutputContract: NormalizedContractSchema;
	templateSetDefaultOutputContract: NormalizedContractSchema;
	templateListInputContract: NormalizedContractSchema;
	templateCollectionOutputContract: NormalizedContractSchema;
	mediaRecordContract: NormalizedContractSchema;
	mediaCollectionOutputContract: NormalizedContractSchema;
	campaignLifecycleInputContract: NormalizedContractSchema;
	campaignLifecycleOutputContract: NormalizedContractSchema;
	campaignPreflightInputContract: NormalizedContractSchema;
	campaignPreflightOutputContract: NormalizedContractSchema;
	campaignScheduleInputContract: NormalizedContractSchema;
	campaignScheduleOutputContract: NormalizedContractSchema;
	subscriberBlocklistInputContract: NormalizedContractSchema;
	subscriberBulkOutputContract: NormalizedContractSchema;
	transactionalSendInputContract: NormalizedContractSchema;
	transactionalSendOutputContract: NormalizedContractSchema;
	sequenceValidateInputContract: NormalizedContractSchema;
	sequenceValidateOutputContract: NormalizedContractSchema;
	sequenceCreateInputContract: NormalizedContractSchema;
	sequenceCreateOutputContract: NormalizedContractSchema;
	sequenceDefinitionOutputContract: NormalizedContractSchema;
	sequenceUpdateInputContract: NormalizedContractSchema;
	sequenceUpdateOutputContract: NormalizedContractSchema;
	sequenceListInputContract: NormalizedContractSchema;
	sequenceListOutputContract: NormalizedContractSchema;
	sequenceIdInputContract: NormalizedContractSchema;
	sequenceDeleteOutputContract: NormalizedContractSchema;
	sequenceEnrollInputContract: NormalizedContractSchema;
	sequenceEnrollOutputContract: NormalizedContractSchema;
	sequenceEnrollmentOutputContract: NormalizedContractSchema;
	sequenceEnrollmentListInputContract: NormalizedContractSchema;
	sequenceEnrollmentListOutputContract: NormalizedContractSchema;
	sequenceEnrollmentGetInputContract: NormalizedContractSchema;
	sequenceTickInputContract: NormalizedContractSchema;
	sequenceTickOutputContract: NormalizedContractSchema;
	sequenceReconcileInputContract: NormalizedContractSchema;
	sequenceReconcileOutputContract: NormalizedContractSchema;
	sequenceStatusInputContract: NormalizedContractSchema;
	sequenceStatusOutputContract: NormalizedContractSchema;
	specSearchInputContract: NormalizedContractSchema;
	specSearchOutputContract: NormalizedContractSchema;
	specDescribeInputContract: NormalizedContractSchema;
	specDescribeOutputContract: NormalizedContractSchema;
	emptyInputContract: NormalizedContractSchema;
	playbookListOutputContract: NormalizedContractSchema;
	playbookGetInputContract: NormalizedContractSchema;
	playbookGetOutputContract: NormalizedContractSchema;
	controlCapabilitiesOutputContract: NormalizedContractSchema;
	controlPrimeInputContract: NormalizedContractSchema;
	controlPrimeOutputContract: NormalizedContractSchema;
	controlStatusInputContract: NormalizedContractSchema;
	controlStatusOutputContract: NormalizedContractSchema;
	providerListInputContract: NormalizedContractSchema;
	providerListOutputContract: NormalizedContractSchema;
	providerIdInputContract: NormalizedContractSchema;
	providerStatusOutputContract: NormalizedContractSchema;
	providerTestOutputContract: NormalizedContractSchema;
	providerQuotaOutputContract: NormalizedContractSchema;
	providerWebhookStatusInputContract: NormalizedContractSchema;
	providerWebhookStatusOutputContract: NormalizedContractSchema;
	deliverabilityDnsCheckOutputContract: NormalizedContractSchema;
	deliverabilityDoctorOutputContract: NormalizedContractSchema;
	webhookListInputContract: NormalizedContractSchema;
	webhookListOutputContract: NormalizedContractSchema;
	webhookCreateInputContract: NormalizedContractSchema;
	webhookCreateOutputContract: NormalizedContractSchema;
	webhookUpdateInputContract: NormalizedContractSchema;
	webhookUpdateOutputContract: NormalizedContractSchema;
	webhookDeleteInputContract: NormalizedContractSchema;
	webhookDeleteOutputContract: NormalizedContractSchema;
	webhookTestInputContract: NormalizedContractSchema;
	webhookTestOutputContract: NormalizedContractSchema;
	webhookDispatchInputContract: NormalizedContractSchema;
	webhookDispatchOutputContract: NormalizedContractSchema;
	webhookDeliveryListInputContract: NormalizedContractSchema;
	webhookDeliveryListOutputContract: NormalizedContractSchema;
	webhookDeliveryRetryInputContract: NormalizedContractSchema;
	webhookDeliveryRetryOutputContract: NormalizedContractSchema;
	webhookReconcileInputContract: NormalizedContractSchema;
	webhookReconcileOutputContract: NormalizedContractSchema;
	webhookPruneInputContract: NormalizedContractSchema;
	webhookPruneOutputContract: NormalizedContractSchema;
	webhookTickInputContract: NormalizedContractSchema;
	webhookTickOutputContract: NormalizedContractSchema;
	webhookRuntimeStatusInputContract: NormalizedContractSchema;
	webhookRuntimeStatusOutputContract: NormalizedContractSchema;
	webhookInboundIngestInputContract: NormalizedContractSchema;
	webhookInboundIngestOutputContract: NormalizedContractSchema;
	webhookDlqListInputContract: NormalizedContractSchema;
	webhookDlqListOutputContract: NormalizedContractSchema;
	webhookDlqReplayInputContract: NormalizedContractSchema;
	webhookDlqReplayOutputContract: NormalizedContractSchema;
	webhookCircuitResetInputContract: NormalizedContractSchema;
	webhookCircuitResetOutputContract: NormalizedContractSchema;
	userRoleManifestReconcileInputContract: NormalizedContractSchema;
	userRoleManifestReconcileOutputContract: NormalizedContractSchema;
	templateManifestReconcileInputContract: NormalizedContractSchema;
	templateManifestReconcileOutputContract: NormalizedContractSchema;
	listCreateInputContract: NormalizedContractSchema;
	listCreateOutputContract: NormalizedContractSchema;
	listUpdateInputContract: NormalizedContractSchema;
	listDeleteInputContract: NormalizedContractSchema;
	listDeleteOutputContract: NormalizedContractSchema;
	subscriberCreateInputContract: NormalizedContractSchema;
	subscriberCreateOutputContract: NormalizedContractSchema;
	subscriberUpdateInputContract: NormalizedContractSchema;
	subscriberDeleteInputContract: NormalizedContractSchema;
	subscriberDeleteOutputContract: NormalizedContractSchema;
	campaignCreateInputContract: NormalizedContractSchema;
	campaignUpdateInputContract: NormalizedContractSchema;
	campaignDeleteInputContract: NormalizedContractSchema;
	campaignDeleteOutputContract: NormalizedContractSchema;
	mediaUploadInputContract: NormalizedContractSchema;
	mediaDeleteInputContract: NormalizedContractSchema;
	mediaDeleteOutputContract: NormalizedContractSchema;
	campaignCloneInputContract: NormalizedContractSchema;
	subscriberBulkListsInputContract: NormalizedContractSchema;
	subscriberBulkBlocklistInputContract: NormalizedContractSchema;
	segmentDriftInputContract: NormalizedContractSchema;
	segmentDriftOutputContract: NormalizedContractSchema;
	dailyDigestInputContract: NormalizedContractSchema;
	dailyDigestOutputContract: NormalizedContractSchema;
	deliverabilityGuardInputContract: NormalizedContractSchema;
	deliverabilityGuardOutputContract: NormalizedContractSchema;
	subscriberHygieneInputContract: NormalizedContractSchema;
	subscriberHygieneOutputContract: NormalizedContractSchema;
	templateRegistrySyncInputContract: NormalizedContractSchema;
	templateRegistrySyncOutputContract: NormalizedContractSchema;
	templateRegistryHistoryOutputContract: NormalizedContractSchema;
	templateIdInputContract: NormalizedContractSchema;
	templatePromoteInputContract: NormalizedContractSchema;
	templatePromoteOutputContract: NormalizedContractSchema;
	templateRollbackInputContract: NormalizedContractSchema;
	templateRollbackOutputContract: NormalizedContractSchema;
	abTestListInputContract: NormalizedContractSchema;
	abTestListOutputContract: NormalizedContractSchema;
	abTestIdInputContract: NormalizedContractSchema;
	abTestGetOutputContract: NormalizedContractSchema;
	abTestCreateInputContract: NormalizedContractSchema;
	abTestCreateOutputContract: NormalizedContractSchema;
	abTestAnalyzeInputContract: NormalizedContractSchema;
	abTestAnalysisOutputContract: NormalizedContractSchema;
	abTestRunInputContract: NormalizedContractSchema;
	abTestTickInputContract: NormalizedContractSchema;
	abTestTickOutputContract: NormalizedContractSchema;
	abTestReconcileInputContract: NormalizedContractSchema;
	abTestReconcileOutputContract: NormalizedContractSchema;
	abTestRecommendSampleSizeInputContract: NormalizedContractSchema;
	abTestRecommendOutputContract: NormalizedContractSchema;
	abTestExportAssignmentInputContract: NormalizedContractSchema;
	abTestExportOutputContract: NormalizedContractSchema;
	abTestDeleteOutputContract: NormalizedContractSchema;
	abTestDeployWinnerOutputContract: NormalizedContractSchema;
}>;

export const campaignGetInputContract = contracts.campaignGetInputContract;
export const campaignGetOutputContract = contracts.campaignGetOutputContract;
export const paginationInputContract = contracts.paginationInputContract;
export const resourceIdInputContract = contracts.resourceIdInputContract;
export const subscriberListRecordContract =
	contracts.subscriberListRecordContract;
export const subscriberListCollectionOutputContract =
	contracts.subscriberListCollectionOutputContract;
export const subscriberRecordContract = contracts.subscriberRecordContract;
export const subscriberListInputContract =
	contracts.subscriberListInputContract;
export const subscriberCollectionOutputContract =
	contracts.subscriberCollectionOutputContract;
export const campaignListInputContract = contracts.campaignListInputContract;
export const campaignCollectionOutputContract =
	contracts.campaignCollectionOutputContract;
export const campaignStatsOutputContract =
	contracts.campaignStatsOutputContract;
export const templateRecordContract = contracts.templateRecordContract;
export const templateCreateInputContract = contracts.templateCreateInputContract;
export const templateUpdateInputContract = contracts.templateUpdateInputContract;
export const templateDeleteOutputContract =
	contracts.templateDeleteOutputContract;
export const templateSetDefaultOutputContract =
	contracts.templateSetDefaultOutputContract;
export const templateListInputContract = contracts.templateListInputContract;
export const templateCollectionOutputContract =
	contracts.templateCollectionOutputContract;
export const mediaRecordContract = contracts.mediaRecordContract;
export const mediaCollectionOutputContract =
	contracts.mediaCollectionOutputContract;
export const campaignLifecycleInputContract =
	contracts.campaignLifecycleInputContract;
export const campaignLifecycleOutputContract =
	contracts.campaignLifecycleOutputContract;
export const campaignPreflightInputContract =
	contracts.campaignPreflightInputContract;
export const campaignPreflightOutputContract =
	contracts.campaignPreflightOutputContract;
export const campaignScheduleInputContract =
	contracts.campaignScheduleInputContract;
export const campaignScheduleOutputContract =
	contracts.campaignScheduleOutputContract;
export const subscriberBlocklistInputContract =
	contracts.subscriberBlocklistInputContract;
export const subscriberBulkOutputContract =
	contracts.subscriberBulkOutputContract;
export const transactionalSendInputContract =
	contracts.transactionalSendInputContract;
export const transactionalSendOutputContract =
	contracts.transactionalSendOutputContract;
export const sequenceValidateInputContract =
	contracts.sequenceValidateInputContract;
export const sequenceValidateOutputContract =
	contracts.sequenceValidateOutputContract;
export const sequenceCreateInputContract =
	contracts.sequenceCreateInputContract;
export const sequenceCreateOutputContract =
	contracts.sequenceCreateOutputContract;
export const sequenceDefinitionOutputContract =
	contracts.sequenceDefinitionOutputContract;
export const sequenceUpdateInputContract =
	contracts.sequenceUpdateInputContract;
export const sequenceUpdateOutputContract =
	contracts.sequenceUpdateOutputContract;
export const sequenceListInputContract = contracts.sequenceListInputContract;
export const sequenceListOutputContract = contracts.sequenceListOutputContract;
export const sequenceIdInputContract = contracts.sequenceIdInputContract;
export const sequenceDeleteOutputContract =
	contracts.sequenceDeleteOutputContract;
export const sequenceEnrollInputContract =
	contracts.sequenceEnrollInputContract;
export const sequenceEnrollOutputContract =
	contracts.sequenceEnrollOutputContract;
export const sequenceEnrollmentOutputContract =
	contracts.sequenceEnrollmentOutputContract;
export const sequenceEnrollmentListInputContract =
	contracts.sequenceEnrollmentListInputContract;
export const sequenceEnrollmentListOutputContract =
	contracts.sequenceEnrollmentListOutputContract;
export const sequenceEnrollmentGetInputContract =
	contracts.sequenceEnrollmentGetInputContract;
export const sequenceTickInputContract = contracts.sequenceTickInputContract;
export const sequenceTickOutputContract = contracts.sequenceTickOutputContract;
export const sequenceReconcileInputContract =
	contracts.sequenceReconcileInputContract;
export const sequenceReconcileOutputContract =
	contracts.sequenceReconcileOutputContract;
export const sequenceStatusInputContract =
	contracts.sequenceStatusInputContract;
export const sequenceStatusOutputContract =
	contracts.sequenceStatusOutputContract;
export const specSearchInputContract = contracts.specSearchInputContract;
export const specSearchOutputContract = contracts.specSearchOutputContract;
export const specDescribeInputContract = contracts.specDescribeInputContract;
export const specDescribeOutputContract = contracts.specDescribeOutputContract;
export const emptyInputContract = contracts.emptyInputContract;
export const playbookListOutputContract =
	contracts.playbookListOutputContract;
export const playbookGetInputContract = contracts.playbookGetInputContract;
export const playbookGetOutputContract = contracts.playbookGetOutputContract;
export const controlCapabilitiesOutputContract =
	contracts.controlCapabilitiesOutputContract;
export const controlPrimeInputContract = contracts.controlPrimeInputContract;
export const controlPrimeOutputContract = contracts.controlPrimeOutputContract;
export const controlStatusInputContract = contracts.controlStatusInputContract;
export const controlStatusOutputContract =
	contracts.controlStatusOutputContract;
export const providerListInputContract = contracts.providerListInputContract;
export const providerListOutputContract = contracts.providerListOutputContract;
export const providerIdInputContract = contracts.providerIdInputContract;
export const providerStatusOutputContract =
	contracts.providerStatusOutputContract;
export const providerTestOutputContract = contracts.providerTestOutputContract;
export const providerQuotaOutputContract =
	contracts.providerQuotaOutputContract;
export const providerWebhookStatusInputContract =
	contracts.providerWebhookStatusInputContract;
export const providerWebhookStatusOutputContract =
	contracts.providerWebhookStatusOutputContract;
export const deliverabilityDnsCheckOutputContract =
	contracts.deliverabilityDnsCheckOutputContract;
export const deliverabilityDoctorOutputContract =
	contracts.deliverabilityDoctorOutputContract;
export const webhookListInputContract = contracts.webhookListInputContract;
export const webhookListOutputContract = contracts.webhookListOutputContract;
export const webhookCreateInputContract = contracts.webhookCreateInputContract;
export const webhookCreateOutputContract = contracts.webhookCreateOutputContract;
export const webhookUpdateInputContract = contracts.webhookUpdateInputContract;
export const webhookUpdateOutputContract =
	contracts.webhookUpdateOutputContract;
export const webhookDeleteInputContract = contracts.webhookDeleteInputContract;
export const webhookDeleteOutputContract = contracts.webhookDeleteOutputContract;
export const webhookTestInputContract = contracts.webhookTestInputContract;
export const webhookTestOutputContract = contracts.webhookTestOutputContract;
export const webhookDispatchInputContract =
	contracts.webhookDispatchInputContract;
export const webhookDispatchOutputContract =
	contracts.webhookDispatchOutputContract;
export const webhookDeliveryListInputContract =
	contracts.webhookDeliveryListInputContract;
export const webhookDeliveryListOutputContract =
	contracts.webhookDeliveryListOutputContract;
export const webhookDeliveryRetryInputContract =
	contracts.webhookDeliveryRetryInputContract;
export const webhookDeliveryRetryOutputContract =
	contracts.webhookDeliveryRetryOutputContract;
export const webhookReconcileInputContract =
	contracts.webhookReconcileInputContract;
export const webhookReconcileOutputContract =
	contracts.webhookReconcileOutputContract;
export const webhookPruneInputContract = contracts.webhookPruneInputContract;
export const webhookPruneOutputContract = contracts.webhookPruneOutputContract;
export const webhookTickInputContract = contracts.webhookTickInputContract;
export const webhookTickOutputContract = contracts.webhookTickOutputContract;
export const webhookRuntimeStatusInputContract =
	contracts.webhookRuntimeStatusInputContract;
export const webhookRuntimeStatusOutputContract =
	contracts.webhookRuntimeStatusOutputContract;
export const webhookInboundIngestInputContract =
	contracts.webhookInboundIngestInputContract;
export const webhookInboundIngestOutputContract =
	contracts.webhookInboundIngestOutputContract;
export const webhookDlqListInputContract =
	contracts.webhookDlqListInputContract;
export const webhookDlqListOutputContract =
	contracts.webhookDlqListOutputContract;
export const webhookDlqReplayInputContract =
	contracts.webhookDlqReplayInputContract;
export const webhookDlqReplayOutputContract =
	contracts.webhookDlqReplayOutputContract;
export const webhookCircuitResetInputContract =
	contracts.webhookCircuitResetInputContract;
export const webhookCircuitResetOutputContract =
	contracts.webhookCircuitResetOutputContract;
export const userRoleManifestReconcileInputContract =
	contracts.userRoleManifestReconcileInputContract;
export const userRoleManifestReconcileOutputContract =
	contracts.userRoleManifestReconcileOutputContract;
export const templateManifestReconcileInputContract =
	contracts.templateManifestReconcileInputContract;
export const templateManifestReconcileOutputContract =
	contracts.templateManifestReconcileOutputContract;
export const listCreateInputContract = contracts.listCreateInputContract;
export const listCreateOutputContract =
	contracts.listCreateOutputContract;
export const listUpdateInputContract = contracts.listUpdateInputContract;
export const listDeleteInputContract = contracts.listDeleteInputContract;
export const listDeleteOutputContract = contracts.listDeleteOutputContract;
export const subscriberCreateInputContract =
	contracts.subscriberCreateInputContract;
export const subscriberCreateOutputContract =
	contracts.subscriberCreateOutputContract;
export const subscriberUpdateInputContract =
	contracts.subscriberUpdateInputContract;
export const subscriberDeleteInputContract =
	contracts.subscriberDeleteInputContract;
export const subscriberDeleteOutputContract =
	contracts.subscriberDeleteOutputContract;
export const campaignCreateInputContract =
	contracts.campaignCreateInputContract;
export const campaignUpdateInputContract =
	contracts.campaignUpdateInputContract;
export const campaignDeleteInputContract =
	contracts.campaignDeleteInputContract;
export const campaignDeleteOutputContract =
	contracts.campaignDeleteOutputContract;
export const mediaUploadInputContract = contracts.mediaUploadInputContract;
export const mediaDeleteInputContract = contracts.mediaDeleteInputContract;
export const mediaDeleteOutputContract = contracts.mediaDeleteOutputContract;
export const campaignCloneInputContract =
	contracts.campaignCloneInputContract;
export const subscriberBulkListsInputContract =
	contracts.subscriberBulkListsInputContract;
export const subscriberBulkBlocklistInputContract =
	contracts.subscriberBulkBlocklistInputContract;
export const segmentDriftInputContract = contracts.segmentDriftInputContract;
export const segmentDriftOutputContract = contracts.segmentDriftOutputContract;
export const dailyDigestInputContract = contracts.dailyDigestInputContract;
export const dailyDigestOutputContract = contracts.dailyDigestOutputContract;
export const deliverabilityGuardInputContract =
	contracts.deliverabilityGuardInputContract;
export const deliverabilityGuardOutputContract =
	contracts.deliverabilityGuardOutputContract;
export const subscriberHygieneInputContract =
	contracts.subscriberHygieneInputContract;
export const subscriberHygieneOutputContract =
	contracts.subscriberHygieneOutputContract;
export const templateRegistrySyncInputContract =
	contracts.templateRegistrySyncInputContract;
export const templateRegistrySyncOutputContract =
	contracts.templateRegistrySyncOutputContract;
export const templateRegistryHistoryOutputContract =
	contracts.templateRegistryHistoryOutputContract;
export const templateIdInputContract = contracts.templateIdInputContract;
export const templatePromoteInputContract =
	contracts.templatePromoteInputContract;
export const templatePromoteOutputContract =
	contracts.templatePromoteOutputContract;
export const templateRollbackInputContract =
	contracts.templateRollbackInputContract;
export const templateRollbackOutputContract =
	contracts.templateRollbackOutputContract;
export const abTestListInputContract = contracts.abTestListInputContract;
export const abTestListOutputContract = contracts.abTestListOutputContract;
export const abTestIdInputContract = contracts.abTestIdInputContract;
export const abTestGetOutputContract = contracts.abTestGetOutputContract;
export const abTestCreateInputContract = contracts.abTestCreateInputContract;
export const abTestCreateOutputContract =
	contracts.abTestCreateOutputContract;
export const abTestAnalyzeInputContract = contracts.abTestAnalyzeInputContract;
export const abTestAnalysisOutputContract = contracts.abTestAnalysisOutputContract;
export const abTestRunInputContract = contracts.abTestRunInputContract;
export const abTestTickInputContract = contracts.abTestTickInputContract;
export const abTestTickOutputContract = contracts.abTestTickOutputContract;
export const abTestReconcileInputContract = contracts.abTestReconcileInputContract;
export const abTestReconcileOutputContract = contracts.abTestReconcileOutputContract;
export const abTestRecommendSampleSizeInputContract = contracts.abTestRecommendSampleSizeInputContract;
export const abTestRecommendOutputContract = contracts.abTestRecommendOutputContract;
export const abTestExportAssignmentInputContract = contracts.abTestExportAssignmentInputContract;
export const abTestExportOutputContract = contracts.abTestExportOutputContract;
export const abTestDeleteOutputContract = contracts.abTestDeleteOutputContract;
export const abTestDeployWinnerOutputContract = contracts.abTestDeployWinnerOutputContract;
