import type { OperationEventSpec } from "./event";

export const resourceLifecycleEventSpecs = [
	{
		type: "list.created",
		title: "Subscriber list created",
		description: "A shared operation created a Listmonk subscriber list.",
		source: "operation",
		subject: "list",
		schemaVersion: 1,
	},
	{
		type: "list.updated",
		title: "Subscriber list updated",
		description: "A shared operation changed a subscriber list.",
		source: "operation",
		subject: "list",
		schemaVersion: 1,
	},
	{
		type: "list.deleted",
		title: "Subscriber list deleted",
		description: "A shared operation deleted a subscriber list.",
		source: "operation",
		subject: "list",
		schemaVersion: 1,
	},
	{
		type: "subscriber.deleted",
		title: "Subscriber deleted",
		description: "A shared operation deleted a subscriber.",
		source: "operation",
		subject: "subscriber",
		schemaVersion: 1,
	},
	{
		type: "subscriber.membership-updated",
		title: "Subscriber memberships updated",
		description: "A bulk operation changed subscriber list memberships.",
		source: "operation",
		subject: "subscriber",
		schemaVersion: 1,
	},
	{
		type: "subscriber.unblocklisted",
		title: "Subscriber unblocklisted",
		description: "A bulk operation removed subscribers from the blocklist.",
		source: "operation",
		subject: "subscriber",
		schemaVersion: 1,
	},
	{
		type: "template.created",
		title: "Template created",
		description: "A shared operation created an email template.",
		source: "operation",
		subject: "template",
		schemaVersion: 1,
	},
	{
		type: "template.updated",
		title: "Template updated",
		description: "A shared operation or registry workflow changed a template.",
		source: "operation",
		subject: "template",
		schemaVersion: 1,
	},
	{
		type: "template.default-set",
		title: "Default template selected",
		description: "A shared operation selected the Listmonk default template.",
		source: "operation",
		subject: "template",
		schemaVersion: 1,
	},
	{
		type: "template.deleted",
		title: "Template deleted",
		description: "A shared operation deleted an email template.",
		source: "operation",
		subject: "template",
		schemaVersion: 1,
	},
	{
		type: "media.uploaded",
		title: "Media uploaded",
		description: "A validated media asset was uploaded to Listmonk.",
		source: "operation",
		subject: "media",
		schemaVersion: 1,
	},
	{
		type: "media.deleted",
		title: "Media deleted",
		description: "A shared operation deleted a media asset.",
		source: "operation",
		subject: "media",
		schemaVersion: 1,
	},
	{
		type: "audience.drift-detected",
		title: "Audience drift detected",
		description: "A segment snapshot crossed its configured drift threshold.",
		source: "operation",
		subject: "audience",
		schemaVersion: 1,
	},
	{
		type: "abtest.created",
		title: "A/B test created",
		description: "An experiment definition was persisted.",
		source: "abtest",
		subject: "experiment",
		schemaVersion: 1,
	},
	{
		type: "abtest.stopped",
		title: "A/B test stopped",
		description: "An experiment was cancelled and cleanup was requested.",
		source: "abtest",
		subject: "experiment",
		schemaVersion: 1,
	},
	{
		type: "abtest.deleted",
		title: "A/B test deleted",
		description: "An experiment was removed from persisted state.",
		source: "abtest",
		subject: "experiment",
		schemaVersion: 1,
	},
	{
		type: "abtest.reconciled",
		title: "A/B test reconciled",
		description: "Experiment state was compared with its remote resources.",
		source: "abtest",
		subject: "experiment",
		schemaVersion: 1,
	},
] as const satisfies readonly OperationEventSpec[];
