import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const projectRoot = resolve(import.meta.dir, "..");
const generatedSourcePath = resolve(projectRoot, ".bunli/commands.gen.ts");
const runtimeMetadataPath = resolve(projectRoot, ".bunli/commands.runtime.mjs");

type GeneratedEntry = { metadata: unknown };

const generatedModule = (await import(pathToFileURL(generatedSourcePath).href)) as {
	generated?: { list?: () => GeneratedEntry[] };
};

const metadataList =
	generatedModule.generated?.list?.().map((entry) => entry.metadata) ?? [];

const content = `// Auto-generated by scripts/generate-completion-metadata.ts
export const generated = {
	list() {
		return ${JSON.stringify(metadataList)}.map((metadata) => ({ metadata }));
	},
};
`;

await mkdir(dirname(runtimeMetadataPath), { recursive: true });
await writeFile(runtimeMetadataPath, content, "utf8");
console.log(`Generated completion metadata:\n- ${runtimeMetadataPath}`);
