// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Abtest from '../src/commands/abtest.js'
import Campaigns from '../src/commands/campaigns.js'
import Examples from '../src/commands/examples.js'
import Lists from '../src/commands/lists.js'
import Status from '../src/commands/status.js'
import Subscribers from '../src/commands/subscribers.js'
import Templates from '../src/commands/templates.js'
import Tx from '../src/commands/tx.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['abtest', 'campaigns', 'examples', 'lists', 'status', 'subscribers', 'templates', 'tx'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'abtest': Abtest,
  'campaigns': Campaigns,
  'examples': Examples,
  'lists': Lists,
  'status': Status,
  'subscribers': Subscribers,
  'templates': Templates,
  'tx': Tx
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'abtest': {
      name: 'abtest',
      description: 'A/B test operations',
      commands: [
        {
          name: 'list',
          description: 'List in-memory A/B tests',
          path: './src/commands/abtest'
        },
        {
          name: 'interactive',
          description: 'Create an A/B test with guided prompts',
          path: './src/commands/abtest'
        },
        {
          name: 'create',
          description: 'Create an A/B test from JSON variant config',
          options: {
            'name': { type: 'z.string.trim.min', required: true, hasDefault: false, description: 'Test name', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":10969,"end":10970,"loc":{"start":{"line":413,"column":39,"index":10969},"end":{"line":413,"column":40,"index":10970}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
            'campaign-id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Base campaign ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' },
            'variants': { type: 'z.string.min', required: true, hasDefault: false, description: 'JSON array of variants', min: 2, minLength: 2, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":11160,"end":11161,"loc":{"start":{"line":419,"column":36,"index":11160},"end":{"line":419,"column":37,"index":11161}},"extra":{"rawValue":2,"raw":"2"},"value":2}}]}, validator: '(val) => true' },
            'lists': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated list IDs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'subject': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Base subject', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'body': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Base body', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'testing-mode': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Testing mode', enumValues: ["holdout","full-split"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'test-group-percentage': { type: 'z.coerce.number.min.max.optional', required: false, hasDefault: false, description: 'Test-group traffic percentage', min: 1, max: 100, minLength: 1, maxLength: 100, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'auto-launch': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Auto-launch the test', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":11815,"end":11820,"loc":{"start":{"line":440,"column":53,"index":11815},"end":{"line":440,"column":58,"index":11820}},"value":false}}]}, validator: '(val) => true' },
            'auto-deploy-winner': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Auto-deploy winning variant', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":11935,"end":11940,"loc":{"start":{"line":443,"column":60,"index":11935},"end":{"line":443,"column":65,"index":11940}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/abtest'
        },
        {
          name: 'analyze',
          description: 'Analyze A/B test results',
          options: {
            'test-id': { type: 'z.string.trim.min', required: true, hasDefault: false, description: 'Test ID', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":12527,"end":12528,"loc":{"start":{"line":464,"column":44,"index":12527},"end":{"line":464,"column":45,"index":12528}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' }
          },
          path: './src/commands/abtest'
        }
      ],
      path: './src/commands/abtest'
    },
  'campaigns': {
      name: 'campaigns',
      description: 'Manage campaigns',
      commands: [
        {
          name: 'list',
          description: 'List campaigns',
          options: {
            'page': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Page number', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'per-page': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Items per page', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'query': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Search query', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/campaigns'
        },
        {
          name: 'get',
          description: 'Get campaign details',
          options: {
            'id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Campaign ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/campaigns'
        }
      ],
      path: './src/commands/campaigns'
    },
  'examples': {
      name: 'examples',
      description: 'Show common command examples',
      path: './src/commands/examples'
    },
  'lists': {
      name: 'lists',
      description: 'Manage subscriber lists',
      commands: [
        {
          name: 'list',
          description: 'List subscriber lists',
          path: './src/commands/lists'
        },
        {
          name: 'get',
          description: 'Get list details',
          options: {
            'id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'List ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/lists'
        }
      ],
      path: './src/commands/lists'
    },
  'status': {
      name: 'status',
      description: 'Check runtime and Listmonk connectivity',
      path: './src/commands/status'
    },
  'subscribers': {
      name: 'subscribers',
      description: 'Manage subscribers',
      commands: [
        {
          name: 'list',
          description: 'List subscribers',
          options: {
            'page': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Page number', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'per-page': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Items per page', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'query': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Search query', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/subscribers'
        },
        {
          name: 'get',
          description: 'Get subscriber details',
          options: {
            'id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Subscriber ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/subscribers'
        },
        {
          name: 'create',
          description: 'Create a subscriber',
          options: {
            'email': { type: 'z.string.trim.email', required: true, hasDefault: false, description: 'Subscriber email', schema: {"type":"zod","method":"email","args":[]}, validator: '(val) => true' },
            'name': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Subscriber name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'lists': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Comma-separated list IDs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'status': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Subscriber status', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/subscribers'
        }
      ],
      path: './src/commands/subscribers'
    },
  'templates': {
      name: 'templates',
      description: 'Manage templates',
      commands: [
        {
          name: 'list',
          description: 'List templates',
          path: './src/commands/templates'
        },
        {
          name: 'get',
          description: 'Get template details',
          options: {
            'id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Template ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/templates'
        },
        {
          name: 'create',
          description: 'Create a template',
          options: {
            'name': { type: 'z.string.trim.min', required: true, hasDefault: false, description: 'Template name', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1740,"end":1741,"loc":{"start":{"line":63,"column":39,"index":1740},"end":{"line":63,"column":40,"index":1741}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
            'type': { type: 'templateTypeSchema.default', required: true, hasDefault: true, default: "campaign", description: 'Template type', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"campaign"}]}, validator: '(val) => true' },
            'subject': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Email subject', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'body': { type: 'z.string.min', required: true, hasDefault: false, description: 'Template body', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":2018,"end":2019,"loc":{"start":{"line":72,"column":32,"index":2018},"end":{"line":72,"column":33,"index":2019}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
            'body-source': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Original source body', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/templates'
        },
        {
          name: 'set-default',
          description: 'Set a template as default',
          options: {
            'id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Template ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/templates'
        }
      ],
      path: './src/commands/templates'
    },
  'tx': {
      name: 'tx',
      description: 'Transactional email operations',
      commands: [
        {
          name: 'send',
          description: 'Send a transactional email',
          options: {
            'template-id': { type: 'z.coerce.number.int.positive', required: true, hasDefault: false, description: 'Template ID', schema: {"type":"zod","method":"positive","args":[]}, validator: '(val) => true' },
            'subscriber-email': { type: 'z.string.trim.email.optional', required: false, hasDefault: false, description: 'Recipient subscriber email', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'subscriber-id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Recipient subscriber ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'from-email': { type: 'z.string.trim.email.optional', required: false, hasDefault: false, description: 'From email address', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'data': { type: 'z.string.optional', required: false, hasDefault: false, description: 'JSON template variables', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'content-type': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Message content type', enumValues: ["html","markdown","plain"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/tx'
        }
      ],
      path: './src/commands/tx'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
